#!/usr/bin/env bash
# sync-lib.sh — being-worker/src/lib/ → lib/ 共通ファイル同期
#
# being-worker/src/lib/ を Single Source of Truth として、
# lib/ の共通ファイルを自動生成する。
#
# 使い方:
#   bash scripts/sync-lib.sh
#
# prebuild で自動実行:
#   npm run build → sync → Next.js build

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."

SRC="$ROOT/being-worker/src/lib"
DST="$ROOT/lib"

# being-worker固有ファイル（除外）
# update-notes.ts は ../../worker/patrol.js 依存があるため除外。
# lib/chat/update-notes.ts はツール定義のみのスタブを手動管理。
EXCLUDE=(
  "chat/act-tool.ts"
  "chat/web-tools.ts"
  "chat/tool-loop-detection.ts"
  "chat/update-notes.ts"
  "chat/system-prompt.ts"
  "keyed-async-queue.ts"
  "memory/embedding.ts"
)

# lib/固有ファイル（保護 — 上書きしない）
PROTECT=(
  "chat/graph.ts"
  "chat/save-session-memory-tool.ts"
  "chat/update-notes.ts"
  "chat/usage.ts"
)

# 除外チェック関数
is_excluded() {
  local rel="$1"
  for ex in "${EXCLUDE[@]}"; do
    [[ "$rel" == "$ex" ]] && return 0
  done
  return 1
}

# 保護チェック関数
is_protected() {
  local rel="$1"
  for prot in "${PROTECT[@]}"; do
    [[ "$rel" == "$prot" ]] && return 0
  done
  return 1
}

# import path 変換
# 引数:
#   $1 = ソースファイルパス
#   $2 = lib/からの相対ディレクトリ（例: "memory", "chat/", ""）
convert_and_copy() {
  local src_file="$1"
  local dst_file="$2"
  local subdir="$3"   # 例: "memory", "chat", "llm", ""

  mkdir -p "$(dirname "$dst_file")"

  {
    echo "// AUTO-GENERATED by scripts/sync-lib.sh — DO NOT EDIT MANUALLY"
    echo "// Source: being-worker/src/lib/$rel"
    echo ""
    # import path変換:
    # 同ディレクトリ内参照 ./xxx.js → @/lib/<subdir>/xxx
    # 親ディレクトリ参照 ../memory/xxx.js → @/lib/memory/xxx
    sed \
      -e "s|from '\.\./memory/\([^']*\)\.js'|from '@/lib/memory/\1'|g" \
      -e "s|from '\.\./llm/\([^']*\)\.js'|from '@/lib/llm/\1'|g" \
      -e "s|from '\.\./chat/\([^']*\)\.js'|from '@/lib/chat/\1'|g" \
      -e "s|from '\.\./utils/\([^']*\)\.js'|from '@/lib/utils/\1'|g" \
      -e "s|from '\.\./\([^']*\)\.js'|from '@/lib/\1'|g" \
      -e "s|from '\./\([^']*\)\.js'|from '@/lib/${subdir}/\1'|g" \
      "$src_file"
  } > "$dst_file"
}

echo "🔄 sync-lib.sh: being-worker/src/lib → lib"

count=0

# being-worker/src/lib 配下を再帰探索
while IFS= read -r -d '' src_file; do
  rel="${src_file#$SRC/}"

  # 除外チェック
  is_excluded "$rel" && continue

  # 保護チェック
  is_protected "$rel" && continue

  dst_file="$DST/$rel"

  # サブディレクトリ名を取得（同一ディレクトリ内importのパス解決用）
  subdir="$(dirname "$rel")"
  [[ "$subdir" == "." ]] && subdir=""

  convert_and_copy "$src_file" "$dst_file" "$subdir"

  count=$((count + 1))
  echo "  ✓ lib/$rel"

done < <(find "$SRC" -name "*.ts" -not -path "*/node_modules/*" -print0 | sort -z)

echo "✅ sync-lib.sh 完了: ${count}ファイル同期"
